
export default {
    LOAD_DATA: 'LOAD_DATA',
    ADD_TO_CART: "ADD_TO_CART",
    ADJUST_ITEM_QTY: "ADJUST_ITEM_QTY",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
    REMOVE_CURRENT_ITEM: "REMOVE_CURRENT_ITEM",
}